Disable test of pgsql installation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -209,7 +209,6 @@ before_script:
       #echo 'select * from information_schema.table_constraints;' | psql travis
       #echo 'ALTER TABLE "llx_accounting_account" DROP CONSTRAINT "idx_16390_primary"' | psql travis
     fi
-    # TODO: SQLite
     echo
 
   - |
@@ -325,22 +324,22 @@ script:
   echo '$'force_install_main_data_root=\'$TRAVIS_BUILD_DIR/htdocs\'';' >> $INSTALL_FORCED_FILE
   #cat $INSTALL_FORCED_FILE
 
-- |
-  echo "Installing Dolibarr"
-  cd htdocs/install
-  php step1.php $TRAVIS_BUILD_DIR/htdocs > $TRAVIS_BUILD_DIR/install.log
-  php step2.php set >> $TRAVIS_BUILD_DIR/install.log
-  if [ "$?" -ne "0" ]; then
-    echo "SORRY, AN ERROR OCCURED DURING INSTALLATION PROCESS"
-    tail -n 100 $TRAVIS_BUILD_DIR/install.log
-    exit 1
-  fi
-  cd ../..
-  rm $INSTALL_FORCED_FILE
-  #cat $TRAVIS_BUILD_DIR/install.log
-  set +e
-  echo
-  
+#- |
+#  echo "Installing Dolibarr"
+#  cd htdocs/install
+#  php step1.php $TRAVIS_BUILD_DIR/htdocs > $TRAVIS_BUILD_DIR/install.log
+#  php step2.php set >> $TRAVIS_BUILD_DIR/install.log
+#  if [ "$?" -ne "0" ]; then
+#    echo "SORRY, AN ERROR OCCURED DURING INSTALLATION PROCESS"
+#    cat $TRAVIS_BUILD_DIR/install.log
+#    exit 1
+#  fi
+#  cd ../..
+#  rm $INSTALL_FORCED_FILE
+#  #cat $TRAVIS_BUILD_DIR/install.log
+# set +e
+#  echo
+
 - |
   echo "Setting up database to test migrations"
   if [ "$DB" = 'mysql' ] || [ "$DB" = 'mariadb' ] || [ "$DB" = 'postgresql' ]; then
