Test CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -224,25 +224,33 @@ before_script:
   - |
     echo "Setting up database"
     if [ "$DB" = 'mysql' ] || [ "$DB" = 'mariadb' ] || [ "$DB" = 'postgresql' ]; then
+      # Ensure we stop on error with set -e
+      set -e
       echo "MySQL drop database"
       mysql -u root -e 'DROP DATABASE IF EXISTS travis;'
       echo "MySQL create database"
       mysql -u root -e "CREATE DATABASE IF NOT EXISTS travis CHARACTER SET = 'utf8';"
       echo "MySQL list current users"
       mysql -u root -e 'use mysql; select * from user;'
-      echo "MySQL create user"
-      mysql -u root -e "CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY 'password';"
+      #echo "MySQL create user"
+      #mysql -u root -e "CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY 'password';"
+      ALTER USER 'root'@'127.0.0.1' IDENTIFIED BY 'password';
       echo "MySQL grant"
       mysql -u root -e 'GRANT ALL PRIVILEGES ON travis.* TO travis@127.0.0.1;'
+      echo "MySQL grant"
+      mysql -u root -e 'GRANT ALL PRIVILEGES ON *.* TO root@127.0.0.1;'
       echo "MySQL flush"
-      mysql -u root -e 'FLUSH PRIVILEGES;'
-      mysql -u root -D travis < dev/initdemo/mysqldump_dolibarr_3.5.0.sql
+      mysql -u root -h 127.0.0.1 -e 'FLUSH PRIVILEGES;'
+      echo "MySQL load no pass"
+      mysql -u root -h 127.0.0.1 -D travis < dev/initdemo/mysqldump_dolibarr_3.5.0.sql
+      echo "MySQL load with pass"
+      mysql -u root -h 127.0.0.1 -D travis < dev/initdemo/mysqldump_dolibarr_3.5.0.sql
     fi
     if [ "$DB" = 'postgresql' ]; then
       echo "PGSQL"
       sudo mkdir -p /tmp/pgloader
       sudo chmod -R a+rwx /tmp/pgloader/
-      sudo pgloader 'mysql://root@localhost/travis' 'postgresql://postgres:postgres@127.0.0.1:5432/travis'
+      sudo pgloader 'mysql://root@127.0.0.1/travis' 'postgresql://postgres:postgres@127.0.0.1:5432/travis'
       echo 'ALTER SEQUENCE llx_accountingaccount_rowid_seq RENAME TO llx_accounting_account_rowid_seq' | psql 'postgresql://postgres:postgres@127.0.0.1:5432/travis'
       echo 'ALTER SEQUENCE llx_accounting_account_rowid_seq RESTART WITH 1000001;' | psql 'postgresql://postgres:postgres@127.0.0.1:5432/travis'
       # Create pgsql compatibility functions
