Doc

diff --git a/.github/workflows/ci-on-pull-checkpr.yml b/.github/workflows/ci-on-pull-checkpr.yml
--- a/.github/workflows/ci-on-pull-checkpr.yml
+++ b/.github/workflows/ci-on-pull-checkpr.yml
@@ -1,10 +1,11 @@
 ---
 # Check the title (label) of a PR starts with a valid keyword (Fix|Close|New|Perf|Doc|Qual|Sec)
-# and make the CI fails, so the PR is refused, if this is not the case.
+# and that the description of the PR does not contain the mention @eldy.
+# If this is not the case, the CI fails, so the PR is refused.
 # Note: the keyword can be in upper or lower case (use upper case to see the PR into the ChangeLog)
 # and must be followed by a space, a '#' or a ':' (for example: "Fix #456 Short description", "Fix: Short description", "New Short description").
 # Draft PRs are skipped (they are not analyzed until they are ready for review).
-name: Check PR title keyword
+name: Check PR title and description
 
 on:
   pull_request:
@@ -13,20 +14,15 @@ on:
 permissions: {}
 
 jobs:
-  check-pr-title:
-    name: Check PR title starts with a valid keyword
+  check-pr:
+    name: Check PR title and description
+    if: github.event.pull_request.draft != true
     runs-on: ubuntu-latest
     steps:
       - name: Check PR title
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
-          PR_IS_DRAFT: ${{ github.event.pull_request.draft }}
         run: |
-          if [ "$PR_IS_DRAFT" = "true" ]; then
-            echo "PR is a draft, title check skipped."
-            exit 0
-          fi
-
           if echo "$PR_TITLE" | grep -Eiq '^(Fix|Close|New|Perf|Doc|Qual|Sec)\b'; then
             echo "Title of PR is valid: '$PR_TITLE'"
             exit 0
@@ -34,3 +30,14 @@ jobs:
 
           echo "::error::The title of the PR must start with one of the keywords (Fix|Close|New|Perf|Doc|Qual|Sec) followed by a space, a ':' (or a '#ID'). Current title: '$PR_TITLE'"
           exit 1
+
+      - name: Check PR description
+        env:
+          PR_BODY: ${{ github.event.pull_request.body }}
+        run: |
+          if echo "$PR_BODY" | grep -Eiq '@eldy\b'; then
+            echo "::error::The description of the PR must not contain the mention of the maintener (@eldy). This is useless as the maintener is already watching and notified for PR."
+            exit 1
+          fi
+
+          echo "Description of PR is valid."
