Update LanguageOfCommentsSniff.php (#38731)
* Update LanguageOfCommentsSniff.php

* Update actions_builddoc.inc.php

* fix

* Update LanguageOfCommentsSniff.php

* Update LanguageOfCommentsSniff.php

* exclude copyright lines

* translate comments

* translate comments

* translate comments

* fix CI

* fix CI

diff --git a/.github/workflows/phpstan.yml b/.github/workflows/phpstan.yml
--- a/.github/workflows/phpstan.yml
+++ b/.github/workflows/phpstan.yml
@@ -63,8 +63,8 @@ jobs:
             phpstan-cache-${{ matrix.php-version }}-${{ github.base_ref }}-
             phpstan-cache-${{ matrix.php-version }}-
 
-      - name: Show debug into
-        run: cd ./.github/tmp && ls -al
+      - name: Show debug info
+        run: ls -al ./.github/tmp || echo "Cache directory not found (first run)"
 
       # Another method to get the list of changed files
       # It sets the variable steps.changed-php.outputs.all_changed_files for other steps
@@ -103,17 +103,17 @@ jobs:
           # shellcheck disable=2086
           if [ "${{ github.ref_name }}" == "develop" ] || [[ "${{ github.ref_name }}" == *.0 ]]|| [[ "${{ github.head_ref }}" == *"phpstan_full"* ]] ; then
             # Run phpstan on all files in integration branch
-            phpstan -vvv analyse --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php | tee _stan.xml | cs2pr --graceful-warnings
+            phpstan analyse --no-progress --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php | tee _stan.xml | cs2pr --graceful-warnings
           else
             PHP_FILES=$(echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | grep -E '\.php$' || true)
             echo "PHP_FILES=$PHP_FILES"
             if [ -z "$PHP_FILES" ]; then
-                echo "No PHP files to analyse. Skipping Phan."
+                echo "No PHP files to analyse. Skipping PHPStan."
                 exit 0
             fi
 
-            echo phpstan -vvv analyse --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php ${ALL_CHANGED_FILES} | tee _stan.xml | cs2pr --graceful-warnings
-            phpstan -vvv analyse --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php ${ALL_CHANGED_FILES} | tee _stan.xml | cs2pr --graceful-warnings
+            echo phpstan analyse --no-progress --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php ${ALL_CHANGED_FILES}
+            phpstan analyse --no-progress --error-format=checkstyle --memory-limit 7G -a dev/build/phpstan/bootstrap_action.php ${ALL_CHANGED_FILES} | tee _stan.xml | cs2pr --graceful-warnings
           fi
         # continue-on-error: true
 
